# These are supported funding model platforms

Paypal: [https://www.paypal.com/donate?hosted_button_id=ACJGZA5K2RWEL]
StreamLabs (Afiliados): [https://streamlabs.com/goprime?promo=aladinoborges-bf81-10]
